gotify:
  url: [[ URL ]]
  apiToken: [[ API_TOKEN ]]
matrix:
  homeserverURL: [[ MATRIX_HOMESERVER_URL]]
  matrixDomain: [[ @bot:[this] ]]
  username: [[ MATRIX_BOT_USERNAME ]]
  token: [[ MATRIX_BOT_API_TOKEN ]]
  roomID: [[ ID_OF_MATRIX_ROOM ]]
  encrypted: [[ true of encryption should be enabled ]]
debug: [[ DEBUG_MODE ]]
